<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="6" failed="2" ignored="0" total="9" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="23664" started-at="2023-06-21T14:50:21Z" finished-at="2023-06-21T14:50:45Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="23664" started-at="2023-06-21T14:50:21Z" finished-at="2023-06-21T14:50:45Z">
      <class name="fbtest.TEST">
        <test-method status="PASS" signature="bfr()[pri:0, instance:fbtest.TEST@185d8b6]" name="bfr" is-config="true" duration-ms="4989" started-at="2023-06-21T14:50:21Z" finished-at="2023-06-21T14:50:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bfr -->
        <test-method status="PASS" signature="bfrmtd()[pri:0, instance:fbtest.TEST@185d8b6]" name="bfrmtd" is-config="true" duration-ms="936" started-at="2023-06-21T14:50:27Z" finished-at="2023-06-21T14:50:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bfrmtd -->
        <test-method status="SKIP" signature="tc1()[pri:0, instance:fbtest.TEST@185d8b6]" name="tc1" duration-ms="8" started-at="2023-06-21T14:50:27Z" finished-at="2023-06-21T14:50:27Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at fbtest.TEST.tc1(TEST.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc1 -->
        <test-method status="PASS" signature="aftmtd()[pri:0, instance:fbtest.TEST@185d8b6]" name="aftmtd" is-config="true" duration-ms="16" started-at="2023-06-21T14:50:27Z" finished-at="2023-06-21T14:50:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftmtd -->
        <test-method status="PASS" signature="bfrmtd()[pri:0, instance:fbtest.TEST@185d8b6]" name="bfrmtd" is-config="true" duration-ms="1154" started-at="2023-06-21T14:50:27Z" finished-at="2023-06-21T14:50:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bfrmtd -->
        <test-method status="SKIP" signature="tc1()[pri:0, instance:fbtest.TEST@185d8b6]" name="tc1" duration-ms="1" started-at="2023-06-21T14:50:29Z" finished-at="2023-06-21T14:50:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at fbtest.TEST.tc1(TEST.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc1 -->
        <test-method status="PASS" signature="aftmtd()[pri:0, instance:fbtest.TEST@185d8b6]" name="aftmtd" is-config="true" duration-ms="8" started-at="2023-06-21T14:50:29Z" finished-at="2023-06-21T14:50:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftmtd -->
        <test-method status="PASS" signature="bfrmtd()[pri:0, instance:fbtest.TEST@185d8b6]" name="bfrmtd" is-config="true" duration-ms="1175" started-at="2023-06-21T14:50:29Z" finished-at="2023-06-21T14:50:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bfrmtd -->
        <test-method status="SKIP" signature="tc1()[pri:0, instance:fbtest.TEST@185d8b6]" name="tc1" duration-ms="4" started-at="2023-06-21T14:50:30Z" finished-at="2023-06-21T14:50:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at fbtest.TEST.tc1(TEST.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc1 -->
        <test-method status="PASS" signature="aftmtd()[pri:0, instance:fbtest.TEST@185d8b6]" name="aftmtd" is-config="true" duration-ms="8" started-at="2023-06-21T14:50:30Z" finished-at="2023-06-21T14:50:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftmtd -->
        <test-method status="PASS" signature="bfrmtd()[pri:0, instance:fbtest.TEST@185d8b6]" name="bfrmtd" is-config="true" duration-ms="1149" started-at="2023-06-21T14:50:30Z" finished-at="2023-06-21T14:50:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bfrmtd -->
        <test-method status="FAIL" signature="tc1()[pri:0, instance:fbtest.TEST@185d8b6]" name="tc1" duration-ms="3" started-at="2023-06-21T14:50:31Z" finished-at="2023-06-21T14:50:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at fbtest.TEST.tc1(TEST.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc1 -->
        <test-method status="PASS" signature="aftmtd()[pri:0, instance:fbtest.TEST@185d8b6]" name="aftmtd" is-config="true" duration-ms="570" started-at="2023-06-21T14:50:31Z" finished-at="2023-06-21T14:50:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftmtd -->
        <test-method status="PASS" signature="bfrmtd()[pri:0, instance:fbtest.TEST@185d8b6]" name="bfrmtd" is-config="true" duration-ms="556" started-at="2023-06-21T14:50:32Z" finished-at="2023-06-21T14:50:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bfrmtd -->
        <test-method status="SKIP" signature="tc2()[pri:0, instance:fbtest.TEST@185d8b6]" name="tc2" duration-ms="102" started-at="2023-06-21T14:50:32Z" finished-at="2023-06-21T14:50:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at fbtest.TEST.tc2(TEST.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
        <test-method status="PASS" signature="aftmtd()[pri:0, instance:fbtest.TEST@185d8b6]" name="aftmtd" is-config="true" duration-ms="11" started-at="2023-06-21T14:50:32Z" finished-at="2023-06-21T14:50:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftmtd -->
        <test-method status="PASS" signature="bfrmtd()[pri:0, instance:fbtest.TEST@185d8b6]" name="bfrmtd" is-config="true" duration-ms="1353" started-at="2023-06-21T14:50:32Z" finished-at="2023-06-21T14:50:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bfrmtd -->
        <test-method status="SKIP" signature="tc2()[pri:0, instance:fbtest.TEST@185d8b6]" name="tc2" duration-ms="65" started-at="2023-06-21T14:50:34Z" finished-at="2023-06-21T14:50:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at fbtest.TEST.tc2(TEST.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
        <test-method status="PASS" signature="aftmtd()[pri:0, instance:fbtest.TEST@185d8b6]" name="aftmtd" is-config="true" duration-ms="6" started-at="2023-06-21T14:50:34Z" finished-at="2023-06-21T14:50:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftmtd -->
        <test-method status="PASS" signature="bfrmtd()[pri:0, instance:fbtest.TEST@185d8b6]" name="bfrmtd" is-config="true" duration-ms="1169" started-at="2023-06-21T14:50:34Z" finished-at="2023-06-21T14:50:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bfrmtd -->
        <test-method status="SKIP" signature="tc2()[pri:0, instance:fbtest.TEST@185d8b6]" name="tc2" duration-ms="71" started-at="2023-06-21T14:50:35Z" finished-at="2023-06-21T14:50:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at fbtest.TEST.tc2(TEST.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
        <test-method status="PASS" signature="aftmtd()[pri:0, instance:fbtest.TEST@185d8b6]" name="aftmtd" is-config="true" duration-ms="8" started-at="2023-06-21T14:50:35Z" finished-at="2023-06-21T14:50:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftmtd -->
        <test-method status="PASS" signature="bfrmtd()[pri:0, instance:fbtest.TEST@185d8b6]" name="bfrmtd" is-config="true" duration-ms="1112" started-at="2023-06-21T14:50:35Z" finished-at="2023-06-21T14:50:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bfrmtd -->
        <test-method status="FAIL" signature="tc2()[pri:0, instance:fbtest.TEST@185d8b6]" name="tc2" duration-ms="77" started-at="2023-06-21T14:50:36Z" finished-at="2023-06-21T14:50:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at fbtest.TEST.tc2(TEST.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
        <test-method status="PASS" signature="aftmtd()[pri:0, instance:fbtest.TEST@185d8b6]" name="aftmtd" is-config="true" duration-ms="13" started-at="2023-06-21T14:50:36Z" finished-at="2023-06-21T14:50:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftmtd -->
        <test-method status="PASS" signature="bfrmtd()[pri:0, instance:fbtest.TEST@185d8b6]" name="bfrmtd" is-config="true" duration-ms="1250" started-at="2023-06-21T14:50:36Z" finished-at="2023-06-21T14:50:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bfrmtd -->
        <test-method status="PASS" signature="tc3()[pri:0, instance:fbtest.TEST@185d8b6]" name="tc3" duration-ms="282" started-at="2023-06-21T14:50:37Z" finished-at="2023-06-21T14:50:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
        <test-method status="PASS" signature="aftmtd()[pri:0, instance:fbtest.TEST@185d8b6]" name="aftmtd" is-config="true" duration-ms="5286" started-at="2023-06-21T14:50:38Z" finished-at="2023-06-21T14:50:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftmtd -->
        <test-method status="PASS" signature="aft()[pri:0, instance:fbtest.TEST@185d8b6]" name="aft" is-config="true" duration-ms="2224" started-at="2023-06-21T14:50:43Z" finished-at="2023-06-21T14:50:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aft -->
      </class> <!-- fbtest.TEST -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
